version: "2"

services:
  php:
    build: "."
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - development.env
    links:
      - serverdb

  nginx:
    image: "nginx:latest"
    working_dir: /app
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - 8080:80
    links:
      - php

  serverdb:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=admin"
      - "MYSQL_DATABASE=homestead"
    ports:
      - "33061:3306"
